name: langchain-aws-service
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - aws-cdk-lib
    - langchain==0.0.220
    - boto3
    - requests
    - streamlit
